### PR TITLE
final change for build ajax_url

### PR DESCRIPTION
**Pull request by Ivanov-Anton**

### CODE REVIEW

**Comment by Ivanov-Anton** [comment]
@tf, Done!

**Comment by tf** [comment]
Why is this needed?

**Comment by Ivanov-Anton** [comment]
> Why is this needed?

I had an error after we merged, but I did not save the error logs

Moreover, I tested this option well yesterday on my project, so it works well

**Comment by Ivanov-Anton** [comment]
I had an error similar to the error from issue #29

undefined method all_options_admin_main_invoices_path' for #<#Class:0x00007fce8737f4a8:0x00007fce8737cfc8>`


that is, the name of the module again got into the name of the route and it gets there where it shouldn't get

**Comment by tf** [comment]
The error surprises me a bit because we no longer use `polymorphic_path` (which calls routes helpers like `all_options_admin_main_invoices_path`). Now we just construct a string.

Also I do not understand what the change does. It basically replaces the `ajax_resource` call with the implementation of the `ajax_resource` method - only that it does not throw an error when the resource can not be found. Still, the call to `option_collection` two lines down also calls `ajax_resource`. So the error should be raised either way. And even if it didn't raise an error, we'd now construct a string of the form `[nil, '/'. 'all_options'].join`, i.e. `/all_options`, which does not make sense to me.

Can you double check what the error looks like in detail when you use 1.4?

**Comment by Ivanov-Anton** [comment]
> The error surprises me a bit because we no longer use `polymorphic_path` (which calls routes helpers like `all_options_admin_main_invoices_path`). Now we just construct a string.
> 
> Also I do not understand what the change does. It basically replaces the `ajax_resource` call with the implementation of the `ajax_resource` method - only that it does not throw an error when the resource can not be found. Still, the call to `option_collection` two lines down also calls `ajax_resource`. So the error should be raised either way. And even if it didn't raise an error, we'd now construct a string of the form `[nil, '/'. 'all_options'].join`, i.e. `/all_options`, which does not make sense to me.
> 
> Can you double check what the error looks like in detail when you use 1.4?

ok but not now after a while thanks

**Comment by tf** [comment]
Of course. No hurry. I tested 1.4 locally in my app and it appears to still work. So if there is something broken, it must be a special case.

**Comment by Ivanov-Anton** [comment]
All is work!

**Pull request closed without merging**
