### PR TITLE
Improve build path for ajax request

### PR DESCRIPTION
**Pull request by Ivanov-Anton**
To prevent error in build path for ajax request when we have namespaced classes
solves #29 issue

- [x] add test that have namespaced class name and use resource settings

### CODE REVIEW

**Comment by Ivanov-Anton** [comment]
@tf  Best Tim

**Comment by tf** [comment]
I pushed two changes: One to make align the new end to end test with the way the existing one worked. And another to simplify the construction of the route. Can you check if I broke anything in your setup?

**Comment by Ivanov-Anton** [comment]
Good job Tim

**Comment by Ivanov-Anton** [comment]
@tf, I have no more offers, everything is fine

**Comment by tf** [comment]
Great! Released as 1.4. Thank you for your work on this issue! :tada:

**Pull request merged**
